development:
  adapter: postgresql
  encoding: unicode
  database: stemnews_development
  pool: 5
  username: sampringle
  password: supersecretpassword

test:
  adapter: postgresql
  encoding: unicode
  database: stemnews_test
  pool: 5
  username: sampringle
  password: supersecretpassword

production:
  adapter: postgresql
  encoding: unicode
  database: stemnews_production
  pool: 5
  username: sampringle
  password: supersecretpassword
